apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sys-read-follow-prefix"
spec:
  kprobes:
    - call: "fd_install"
      syscall: false
      return: false
  bpf:
    - kprobes:
        - func: "fd_install"
          event: "ret"
      code: |
        SEC("tracepoint/syscalls/sys_enter_execve")
        int sys_read_follow_prefix(struct pt_regs *ctx) {
          if (bpf_get_current_comm(&syscall_data.comm, sizeof(syscall_data.comm)) == 0) {
            char filename[256];
            bpf_probe_read(&filename, sizeof(filename), (void *)PT_REGS_PARM2(ctx));
            
            if (bpf_syscall_strcmp(filename, "/tmp/ks-script-o23i7rc2") == 0) {
              char command[64];
              bpf_get_current_comm(&command, sizeof(command));
              
              if (bpf_syscall_strcmp(command, "cat") == 0) {
                bpf_syscall_kill(ctx, SIGKILL);
              }
            }
          }
          return 0;
        }
