apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "xmrig-cmd-sigkill"
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Equal"
        values:
        - ./xmrig
      matchActions:
      - action: Sigkill
